name: Build and Release

on:
  push:
    branches:
      - master  # 当提交以 v 开头的标签时触发

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]  # 在 macOS 和 Windows 环境中运行

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2  # 检出代码

      - name: Install Node.js
        uses: actions/setup-node@v2  # 设置 Node.js 环境
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install  # 安装项目依赖


      - name: Package the app
        run: npm run make  # 使用 Electron Forge 打包应用

      - name: Publish the app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub Token，用于发布 Release
        run: npm run publish -- --publish always  # 发布应用
